name: .NET Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install Dokan
      run: choco install dokany
    - run: git clone https://github.com/dokan-dev/dokan-dotnet
#    - run: git clone https://github.com/StevenBonePgh/SevenZipSharp
    - run: git clone https://github.com/meee1/Shaman.Dokan.Base
    - name: Add package Shaman.SevenZipSharp
      run: dotnet add Shaman.Dokan.Archive package Shaman.SevenZipSharp --version 1.0.6.3
    - name: Build with dotnet
      run: dotnet build --configuration Release Shaman.Dokan.Archive
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .
