name: .NET Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install Dokan
      run: choco install dokany
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .
